version: 2.0.{build}
image: Visual Studio 2017
configuration: Release
clone_folder: C:\Git\
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
after_build:
- cmd: nuget pack Amoenus.NoneForLinq\Package.nuspec -Version %appveyor_build_version%
artifacts:
- path: '**\Amoenus.NoneForLinq*.nupkg' 
  name: packages 
on_success:
- ps: >-
    git config --global credential.helper store

    Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"

    git tag -a release/$($env:APPVEYOR_BUILD_VERSION)

    git push origin release/$($env:APPVEYOR_BUILD_VERSION)