version: 2.0.{build}
image: Visual Studio 2017
configuration: Release
clone_folder: C:\Git\
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
after_build:
- cmd: nuget pack Amoenus.NoneForLinq\Package.nuspec -Version %appveyor_build_version%
artifacts:
- path: '**\Amoenus.NoneForLinq*.nupkg'
  name: packages
on_success:
  - ps: |    
        git checkout "$env:APPVEYOR_REPO_BRANCH"
        git config --global core.autocrlf true
        git config --global credential.helper store 
        Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
        git remote add neworigin "$env:github_repo"
        git config --global user.email "$env:github_email"
        git config --global user.name "$env:github_user"
        git add .
        git commit -m "Updated biicode parents [skip ci]"
        git push neworigin "$env:APPVEYOR_REPO_BRANCH"